name: Project2 Tests

on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:
    
jobs:
    app_tests:
        runs-on: ubuntu-latest
        steps:

            # Configure Environment
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install Python
              id: setup-python
              uses: actions/setup-python@v4
              with:
                python-version: 3.9
            
            # Prepare Poetry
            - name: Load cached Poetry install
              uses: actions/cache@v3
              id: cached-poetry
              with:
                path: ./.poetry
                key: venv::${{ runner.os }}::${{ steps.setup-python.outputs.python-version }}::poetry
            - name: Install Poetry
              if: steps.cached-poetry.outputs.cache-hit != 'true'
              run: | 
                python -m venv .poetry
                source ./.poetry/bin/activate
                pip install poetry
                deactivate
            - name: Add Poetry to PATH
              run: alias poetry="$PWD/.poetry/bin/poetry"
            - name: Configure Poetry
              run: poetry config virtualenvs.in-project true
            
            # Prepare Virtual Environment
            - name: Load cached virtual environment
              uses: actions/cache@v3
              id: cached-dependencies
              with:
                path: ./project2/.venv
                key: venv::${{ runner.os }}::${{ steps.setup-python.outputs.python-version }}::${{ hashFiles('./project2/poetry.lock') }}
            - name: Install dependencies
              if: steps.cached-dependencies.outputs.cache-hit != 'true'
              working-directory: ./project2
              run: poetry install --no-interaction --no-root
            - name: Install project
              working-directory: ./project2
              run: poetry install --no-interaction --only-root
            
            # Check Lint, Test, Security
            - name: Lint Project2
              working-directory: ./project2
              run: poetry run invoke lint
            - name: Test Project2
              working-directory: ./project2
              run: poetry run invoke test
            - name: Run Bandit security check
              working-directory: ./project2
              run: poetry run bandit -r ./test_project_2 -ll -ii
            - name: Safety vulnerability check
              working-directory: ./project2
              run: poetry export -f requirements.txt | poetry run safety check --full-report --stdin
